apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: job-pyspark-{{ macros.datetime.now().strftime("%Y-%m-%d-%H-%M-%S") }}
  namespace: airflow
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "gcr.io/spark-operator/spark-py:v3.1.1"
  imagePullPolicy: Always
  mainApplicationFile: gs://edc-scripts/converte_parquet.py
  sparkVersion: "3.1.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  hadoopConf:
    "fs.gs.project.id": "edc-desafio-igti"
    "fs.gs.system.bucket": "desafio-igti"
    "google.cloud.auth.service.account.enable": "true"
    "google.cloud.auth.service.account.json.keyfile": "../../config"
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "4g"
    secrets:
    - name: "gcs-bq"
      path: "/mnt/secrets"
      secretType: GCPServiceAccount
    envVars:
      GCS_PROJECT_ID: edc-desafio-igti
    serviceAccount: spark
    labels:
      version: 3.1.1
  executor:
    cores: 3
    memory: "4g"
    secrets:
    - name: "gcs-bq"
      path: "../../config/edc-desafio-igti-32c40cffbfdd.json"
      secretType: GCPServiceAccount
    envVars:
      GCS_PROJECT_ID: edc-desafio-igti
    instances: 3
    labels:
      version: 3.1.1
